[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  framework = "#static"

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/strava-auth"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

# Disable Netlify admin toolbar
[context.production]
  environment = { NETLIFY_DISABLE_TOOLBAR = "true" }
